# Generated by Django 4.2.11 on 2024-03-18 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('difficulty', models.IntegerField()),
                ('score_id', models.IntegerField()),
                ('challenge_score', models.IntegerField(default=0)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('level_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.level')),
            ],
        ),
    ]
