# Generated by Django 4.2.11 on 2024-03-18 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_basicchallenge'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaChallenge',
            fields=[
                ('basicchallenge_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basicchallenge')),
                ('area', models.TextField()),
                ('photo_link', models.URLField()),
            ],
            bases=('core.basicchallenge',),
        ),
        migrations.CreateModel(
            name='CoordinateChallenge',
            fields=[
                ('basicchallenge_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basicchallenge')),
                ('lat', models.TextField()),
                ('long', models.TextField()),
                ('photo_link', models.URLField()),
            ],
            bases=('core.basicchallenge',),
        ),
        migrations.CreateModel(
            name='SimpleChallenge',
            fields=[
                ('basicchallenge_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basicchallenge')),
                ('photo_link', models.URLField()),
            ],
            bases=('core.basicchallenge',),
        ),
    ]
